# docker-compose.yml

version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - '5432:5432'
    volumes:
      - addressbook-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  addressbook:
    build:
      context: .
    environment:
      - DB_SCHEMA=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - NODE_ENV=test
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    ports:
      - '3000:3000'
    # Default command for running tests
    command: npm test
        
volumes:
  addressbook-db:

networks:
  app-network:
    driver: bridge